version: 18.04
os: ubuntu
files:
  - source: /index.php
    destination: /var/www/html/php-helloworld
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root 
  ApplicationStart:
    - location: scripts/start_server.sh   
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
